spring.application.name=storeapi
spring.datasource.url=jdbc:mysql://localhost:3306/store_directory
spring.datasource.username=root
spring.datasource.password=omar5632
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always